### ISSUE TITLE
Test other RNGs

### ISSUE THREAD

**Issue by prbzrg** [LuxDL/WeightInitializers.jl#11]
It would be good to test how other RNGs works with the APIs.

- [ ] AMDGPU.rocrand_rng()
- [ ] AMDGPU.gpuarrays_rng()
- [ ] Metal.gpuarrays_rng()
- [ ] oneAPI.gpuarrays_rng()

**Comment by avik-pal** [comment]
We should revisit this now. `LuxDeviceUtils` now exports a `default_device_rng(...)`, so I would expect all the initializers to work with that.
