### ISSUE TITLE
Add type check and conversion for kwargs

### ISSUE THREAD

**Issue by MartinuzziFrancesco** [LuxDL/WeightInitializers.jl#21]
Ideally we would add a check to convert user given kwargs to the same type as specified by `::Type{T}`. Something like `gain = gain isa T ? gain : convert(T, gain)`. At the moment we either force the conversion like [here](https://github.com/LuxDL/WeightInitializers.jl/blob/main/src/initializers.jl#L59) or it goes unnoticed like [here](https://github.com/LuxDL/WeightInitializers.jl/blob/main/src/initializers.jl#L78). 

Currently the following code returns a Float64, adding the check would make the workflow less cumbersome since it avoids the user the step of always double checking and converting the kwargs types

```julia
weights_cl = kaiming_normal(Float16; gain=1.0)
weights = weights_cl(2, 5)
#2×5 Matrix{Float64}:
# -0.160808  -0.187664   0.187882  0.918777  -0.136354
#  0.486026   0.321397  -0.30655   0.145306   0.206441
```

I can get this on its way, I just wanted to check if it's something worth implementing.

We also should cover this case in the tests, I don't think the kwargs typing is being tested at the moment

**Comment by avik-pal** [comment]
yeah this should be handled
